// This code snippet was auto generated by xls2vlog.py from source file: ./user_project_wrapper.xlsx
// User: josh
// Date: Sep-22-23



module USER_PRJ1 #(
    parameter pUSER_PROJECT_SIDEBAND_WIDTH = 5,
    parameter pADDR_WIDTH = 12,
    parameter pDATA_WIDTH = 32
) (
    // ---------- AXI-lite ----------
    // AR channel
    input  wire                     arvalid,
    input  wire [11:0]              araddr,
    output wire                     arready,
    // R channel
    input  wire                     rready,
    output wire                     rvalid,
    output wire [(pDATA_WIDTH-1):0] rdata,
    // AW channel
    input  wire                     awvalid,
    input  wire [11:0]              awaddr,
    output wire                     awready,
    // W channel
    input  wire                     wvalid,
    input  wire [3:0]               wstrb,
    input  wire [(pDATA_WIDTH-1):0] wdata,
    output wire                     wready,
    // ---------- AXI-stream (modified) ----------
    // Slave
    input  wire                     ss_tvalid,
    input  wire [(pDATA_WIDTH-1):0] ss_tdata,
    input  wire                     ss_tlast,
    input  wire [1:0]               ss_tuser,
    input  wire [3:0]               ss_tstrb,
    input  wire [3:0]               ss_tkeep,
    output wire                     ss_tready,
`ifdef USER_PROJECT_SIDEBAND_SUPPORT
    input  wire [(pUSER_PROJECT_SIDEBAND_WIDTH-1):0] ss_tupsb,
`endif
    // Master
    input  wire                     sm_tready,
    output wire                     sm_tvalid,
    output wire [(pDATA_WIDTH-1):0] sm_tdata,
    output wire                     sm_tlast,
    output wire [2:0]               sm_tid,
    output wire [3:0]               sm_tstrb,
    output wire [3:0]               sm_tkeep,   
`ifdef USER_PROJECT_SIDEBAND_SUPPORT
    output wire [(pUSER_PROJECT_SIDEBAND_WIDTH-1):0] sm_tupsb,
`endif
    // ---------- Interrupt request ---------
    output wire                     low__pri_irq,
    output wire                     High_pri_req,
    // ---------- Logic analizyer ---------- 
    output wire [23:0]              la_data_o,
    // ---------- Clock & Reset ----------
    input  wire                     axi_clk,
    input  wire                     axis_clk,
    input  wire                     axi_reset_n,
    input  wire                     axis_rst_n,
    input  wire                     user_clock2,
    input  wire                     uck2_rst_n
);

assign wstrb = 4'b1111;
assign sm_tid        = 3'b0;
assign sm_tstrb      = 4'b1111;
assign sm_tkeep      = 1'b1111;
`ifdef USER_PROJECT_SIDEBAND_SUPPORT
assign sm_tupsb      = 5'b0;
`endif

assign low__pri_irq  = 1'b0;
assign High_pri_req  = 1'b0;
assign la_data_o     = 24'b0;

// ========== Module Instanciate =============
Fir #(
    .pADDR_WIDTH(12),
    .pDATA_WIDTH(32),
    .Tape_Num   (11)
) fir (
    //---------- AXI-lite slave Interface ----------
    // Address write channel
    .awready    (awready),
    .awvalid    (awvalid),
    .awaddr     (awaddr),
    // Write channel
    .wready     (wready),
    .wvalid     (wvalid),
    .wdata      (wdata),
    // Address read channel
    .arready    (arready),
    .arvalid    (arvalid),
    .araddr     (araddr),
    // Read channel
    .rvalid     (rvalid),
    .rdata      (rdata),
    .rready     (rready),
    //---------- AXI-stream Interface ----------
    // Slave
    .ss_tvalid  (ss_tvalid),
    .ss_tdata   (ss_tdata),
    .ss_tlast   (ss_tlast),
    .ss_tready  (ss_tready),
    // Master
    .sm_tready  (sm_tready),
    .sm_tvalid  (sm_tvalid),
    .sm_tdata   (sm_tdata),
    .sm_tlast   (sm_tlast),

    .axis_clk   (axis_clk),
    .axis_rst_n (axis_rst_n)
);

endmodule // USER_PRJ1
